In [67]:
"""This is a Data Cleaning Execise"""

import pandas as pd

In [68]:
#step 1 : replace Nulls By NA value

df = pd.read_csv("risk_factors_cervical_cancer.csv",na_values=["?"," ?","? "])

In [69]:
df.shape

(858, 36)

In [70]:
df.head()

,Age,Number of sexual partners,First sexual intercourse,Num of pregnancies,Smokes,Smokes (years),Smokes (packs/year),Hormonal Contraceptives,Hormonal Contraceptives (years),IUD,...,STDs: Time since first diagnosis,STDs: Time since last diagnosis,Dx:Cancer,Dx:CIN,Dx:HPV,Dx,Hinselmann,Schiller,Citology,Biopsy
0,18,4.0,15.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
1,15,1.0,14.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
2,34,1.0,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
3,52,5.0,16.0,4.0,1.0,37.0,37.0,1.0,3.0,0.0,...,NaN,NaN,1,0,1,0,0,0,0,0
4,46,3.0,21.0,4.0,0.0,0.0,0.0,1.0,15.0,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0

In [57]:
#step 2:  Remove unneccessary columns (as per the description)
# no such column availavble 
# step 3 : binarise the targetvariable
# imp column are last 4 
print(df['Hinselmann'].unique())
print(df['Schiller'].unique())
print(df['Citology'].unique())
print(df['Biopsy'].unique())
x= (df['Hinselmann']+df['Schiller']+df['Citology']+df['Biopsy'])
x.unique()

[0 1]
[0 1]
[0 1]
[0 1]

array([0, 3, 1, 2, 4], dtype=int64)

In [71]:
#2
df['Cancer']=(df['Hinselmann']+df['Schiller']+df['Citology']+df['Biopsy'])

In [72]:
#2
df.loc[df['Cancer'] > 0, 'Cancer'] = 1

In [73]:
#2
df['Cancer'].unique()

array([0, 1], dtype=int64)

In [74]:
df.shape

(858, 37)

In [48]:
# step 3: Format or Binarize the target or unknown variable
df['Cancer'].unique()

array([0, 1], dtype=int64)

In [75]:
# step 4 :  Check datatypes, handle columns with Object / string type (either convert to number / remove them)
df.dtypes

Age                                     int64
Number of sexual partners             float64
First sexual intercourse              float64
Num of pregnancies                    float64
Smokes                                float64
Smokes (years)                        float64
Smokes (packs/year)                   float64
Hormonal Contraceptives               float64
Hormonal Contraceptives (years)       float64
IUD                                   float64
IUD (years)                           float64
STDs                                  float64
STDs (number)                         float64
STDs:condylomatosis                   float64
STDs:cervical condylomatosis          float64
STDs:vaginal condylomatosis           float64
STDs:vulvo-perineal condylomatosis    float64
STDs:syphilis                         float64
STDs:pelvic inflammatory disease      float64
STDs:genital herpes                   float64
STDs:molluscum contagiosum            float64
STDs:AIDS                             float64
STDs:HIV                              float64
STDs:Hepatitis B                      float64
STDs:HPV                              float64
STDs: Number of diagnosis               int64
STDs: Time since first diagnosis      float64
STDs: Time since last diagnosis       float64
Dx:Cancer                               int64
Dx:CIN                                  int64
Dx:HPV                                  int64
Dx                                      int64
Hinselmann                              int64
Schiller                                int64
Citology                                int64
Biopsy                                  int64
Cancer                                  int64
dtype: object

In [76]:
# step 5: Remove columns which have all missing / NA values
df.isnull().all()

Age                                   False
Number of sexual partners             False
First sexual intercourse              False
Num of pregnancies                    False
Smokes                                False
Smokes (years)                        False
Smokes (packs/year)                   False
Hormonal Contraceptives               False
Hormonal Contraceptives (years)       False
IUD                                   False
IUD (years)                           False
STDs                                  False
STDs (number)                         False
STDs:condylomatosis                   False
STDs:cervical condylomatosis          False
STDs:vaginal condylomatosis           False
STDs:vulvo-perineal condylomatosis    False
STDs:syphilis                         False
STDs:pelvic inflammatory disease      False
STDs:genital herpes                   False
STDs:molluscum contagiosum            False
STDs:AIDS                             False
STDs:HIV                              False
STDs:Hepatitis B                      False
STDs:HPV                              False
STDs: Number of diagnosis             False
STDs: Time since first diagnosis      False
STDs: Time since last diagnosis       False
Dx:Cancer                             False
Dx:CIN                                False
Dx:HPV                                False
Dx                                    False
Hinselmann                            False
Schiller                              False
Citology                              False
Biopsy                                False
Cancer                                False
dtype: bool

In [77]:
# Drop columns which have all NaN values
l=df.columns[df.isnull().all()]
df.drop(l, inplace=True, axis=1)

In [82]:
df.shape

858

In [83]:

df.isnull().sum()/df.shape[0]*100

Age                                    0.000000
Number of sexual partners              3.030303
First sexual intercourse               0.815851
Num of pregnancies                     6.526807
Smokes                                 1.515152
Smokes (years)                         1.515152
Smokes (packs/year)                    1.515152
Hormonal Contraceptives               12.587413
Hormonal Contraceptives (years)       12.587413
IUD                                   13.636364
IUD (years)                           13.636364
STDs                                  12.237762
STDs (number)                         12.237762
STDs:condylomatosis                   12.237762
STDs:cervical condylomatosis          12.237762
STDs:vaginal condylomatosis           12.237762
STDs:vulvo-perineal condylomatosis    12.237762
STDs:syphilis                         12.237762
STDs:pelvic inflammatory disease      12.237762
STDs:genital herpes                   12.237762
STDs:molluscum contagiosum            12.237762
STDs:AIDS                             12.237762
STDs:HIV                              12.237762
STDs:Hepatitis B                      12.237762
STDs:HPV                              12.237762
STDs: Number of diagnosis              0.000000
STDs: Time since first diagnosis      91.724942
STDs: Time since last diagnosis       91.724942
Dx:Cancer                              0.000000
Dx:CIN                                 0.000000
Dx:HPV                                 0.000000
Dx                                     0.000000
Hinselmann                             0.000000
Schiller                               0.000000
Citology                               0.000000
Biopsy                                 0.000000
Cancer                                 0.000000
dtype: float64

In [84]:
#step 6 : Remove rows with missing / NA values greater than 50%
# drop columns with NAN nore than 90%
#(df.isnull().sum()/df.shape[0]) *100 # more than 90% null values


l=df.columns[((df.isnull().sum() / df.shape[0]) *100) > 90]
df.drop(l ,inplace=True,axis=1)

In [85]:
df.shape

(858, 35)

In [87]:
# Find rows with missing values greater than 50%
df[    df.isnull().sum(axis=1)    >   (df.shape[1]/2)   ]
df = df[df.isnull().sum(axis=1) <=(df.shape[1]/2) ]

In [88]:
df.shape

(763, 35)

In [61]:
#Step 7: Fill missing / NA values using central tendencies
# Fill missing values with mode value for all columns which are float or int

for col in df.columns[df.isnull().any()]:
    df[col].fillna(df[col].mode()[0],inplace=True)

# Print remaining columns which still have NaN values
#[0] for index of mode

df.columns[df.isnull().any()]

Index([], dtype='object')

In [89]:
# Print colmuns that have minimum one NaN value
len(df.columns[df.isna().any()])

24

In [90]:
df.shape

(763, 35)

In [91]:
# Fill missing values with mode value for all columns which are float or int
for col in df.columns[df.isnull().any()]:
    df[col].fillna(df[col].mode()[0],inplace=True)
# Print remaining columns which still have NaN values
df.columns[df.isnull().any()]

Index([], dtype='object')

In [92]:
df.shape

(763, 35)

In [93]:
# Check those columns where all values are same
(df != df.iloc[0]).any()
# (df == df.iloc[0]).all()

Age                                    True
Number of sexual partners              True
First sexual intercourse               True
Num of pregnancies                     True
Smokes                                 True
Smokes (years)                         True
Smokes (packs/year)                    True
Hormonal Contraceptives                True
Hormonal Contraceptives (years)        True
IUD                                    True
IUD (years)                            True
STDs                                   True
STDs (number)                          True
STDs:condylomatosis                    True
STDs:cervical condylomatosis          False
STDs:vaginal condylomatosis            True
STDs:vulvo-perineal condylomatosis     True
STDs:syphilis                          True
STDs:pelvic inflammatory disease       True
STDs:genital herpes                    True
STDs:molluscum contagiosum             True
STDs:AIDS                             False
STDs:HIV                               True
STDs:Hepatitis B                       True
STDs:HPV                               True
STDs: Number of diagnosis              True
Dx:Cancer                              True
Dx:CIN                                 True
Dx:HPV                                 True
Dx                                     True
Hinselmann                             True
Schiller                               True
Citology                               True
Biopsy                                 True
Cancer                                 True
dtype: bool

In [94]:
# Remove columns which have same value in all rows
df=df.loc[:, (df != df.iloc[0]).any()]
df.shape

(763, 33)

In [95]:
for col in df.columns:
    if len(df[col].unique()) == df.shape[0]:
        print(col)
#         df.drop(col,inplace=True,axis=1)

In [96]:
df.shape

(763, 33)

In [97]:
# step 9 : Remove columns which have different values in all rows
#Remove the columns where all values are different
#Example columns V1
for col in df.columns:
    if len(df[col].unique()) == df.shape[0]:
           print(col);
    # df.drop(col,inplace=True,axis=1)
######
#Problem :: A continous variable may get removed!!!!!
######

In [98]:
df.shape

(763, 33)

In [99]:
df.describe(include= 'all') 
# Get statistical description of each column in data frame

,Age,Number of sexual partners,First sexual intercourse,Num of pregnancies,Smokes,Smokes (years),Smokes (packs/year),Hormonal Contraceptives,Hormonal Contraceptives (years),IUD,...,STDs: Number of diagnosis,Dx:Cancer,Dx:CIN,Dx:HPV,Dx,Hinselmann,Schiller,Citology,Biopsy,Cancer
count,763.000000,763.000000,763.000000,763.000000,763.000000,763.000000,763.000000,763.000000,763.000000,763.000000,...,763.000000,763.000000,763.000000,763.000000,763.000000,763.000000,763.000000,763.000000,763.000000,763.000000
mean,27.201835,2.513761,17.069463,2.231979,0.141547,1.220005,0.462098,0.647444,2.217974,0.108781,...,0.098296,0.023591,0.010485,0.023591,0.030144,0.045872,0.096986,0.055046,0.072084,0.131062
std,8.658353,1.662701,2.830588,1.456247,0.348813,4.140635,2.287061,0.478079,3.743427,0.311569,...,0.319177,0.151871,0.101925,0.151871,0.171096,0.209344,0.296132,0.228219,0.258796,0.337689
min,13.000000,1.000000,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,21.000000,2.000000,15.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,26.000000,2.000000,17.000000,2.000000,0.000000,0.000000,0.000000,1.000000,0.420000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,33.000000,3.000000,18.000000,3.000000,0.000000,0.000000,0.000000,1.000000,3.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,84.000000,28.000000,32.000000,11.000000,1.000000,37.000000,37.000000,1.000000,30.000000,1.000000,...,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [100]:
# Normalize the data
from sklearn import preprocessing

x = df.values #returns a numpy array
min_max_scaler = preprocessing.MinMaxScaler() # MinMaxScalar() fixes all values between 0 to 1
x_scaled = min_max_scaler.fit_transform(x)
df = pd.DataFrame(x_scaled,columns=df.columns)

In [26]:
df.describe()

,Age,Number of sexual partners,First sexual intercourse,Num of pregnancies,Smokes,Smokes (years),Smokes (packs/year),Hormonal Contraceptives,Hormonal Contraceptives (years),IUD,...,STDs: Number of diagnosis,Dx:Cancer,Dx:CIN,Dx:HPV,Dx,Hinselmann,Schiller,Citology,Biopsy,Cancer
count,858.000000,858.000000,858.000000,858.000000,858.000000,858.000000,858.000000,858.000000,858.000000,858.000000,...,858.000000,858.000000,858.000000,858.000000,858.000000,858.000000,858.000000,858.000000,858.000000,858.000000
mean,0.194655,0.055987,0.317228,0.199301,0.143357,0.032466,0.012062,0.686480,0.065746,0.096737,...,0.029138,0.020979,0.010490,0.020979,0.027972,0.040793,0.086247,0.051282,0.064103,0.118881
std,0.119689,0.060917,0.127166,0.130400,0.350641,0.109747,0.059739,0.464194,0.119930,0.295771,...,0.100848,0.143398,0.101939,0.143398,0.164989,0.197925,0.280892,0.220701,0.245078,0.323837
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.098592,0.037037,0.227273,0.090909,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.169014,0.037037,0.318182,0.181818,0.000000,0.000000,0.000000,1.000000,0.008333,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.267606,0.074074,0.363636,0.272727,0.000000,0.000000,0.000000,1.000000,0.066667,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [89]:
# Standard SCAling       : mean =0 and std div = 1 
from sklearn import preprocessing
x = df.values #returns a numpy array
min_max_scaler = preprocessing.StandardScaler()   # Standard Sacler()
x_scaled_std = min_max_scaler.fit_transform(x)
df = pd.DataFrame(x_scaled_std,columns=df.columns)

In [90]:
df.describe()

,Age,Number of sexual partners,First sexual intercourse,Num of pregnancies,Smokes,Smokes (years),Smokes (packs/year),Hormonal Contraceptives,Hormonal Contraceptives (years),IUD,...,STDs: Number of diagnosis,Dx:Cancer,Dx:CIN,Dx:HPV,Dx,Hinselmann,Schiller,Citology,Biopsy,Cancer
count,8.580000e+02,8.580000e+02,8.580000e+02,8.580000e+02,8.580000e+02,8.580000e+02,8.580000e+02,8.580000e+02,8.580000e+02,8.580000e+02,...,8.580000e+02,8.580000e+02,8.580000e+02,8.580000e+02,8.580000e+02,8.580000e+02,8.580000e+02,8.580000e+02,8.580000e+02,8.580000e+02
mean,4.746915e-16,1.251265e-16,3.064112e-16,-6.534529e-17,7.466185e-17,-8.371962e-17,-1.245442e-16,3.796497e-16,3.967947e-16,3.079640e-16,...,-8.850729e-17,9.627109e-17,-7.132989e-17,2.846726e-16,-2.967712e-16,6.598581e-16,3.736974e-16,-2.483768e-16,-9.200100e-17,-1.018351e-16
std,1.000583e+00,1.000583e+00,1.000583e+00,1.000583e+00,1.000583e+00,1.000583e+00,1.000583e+00,1.000583e+00,1.000583e+00,1.000583e+00,...,1.000583e+00,1.000583e+00,1.000583e+00,1.000583e+00,1.000583e+00,1.000583e+00,1.000583e+00,1.000583e+00,1.000583e+00,1.000583e+00
min,-1.627284e+00,-9.196100e-01,-2.496053e+00,-1.529276e+00,-4.090806e-01,-2.959993e-01,-2.020215e-01,-1.479727e+00,-5.485287e-01,-3.272564e-01,...,-2.890930e-01,-1.463850e-01,-1.029597e-01,-1.463850e-01,-1.696378e-01,-2.062216e-01,-3.072259e-01,-2.324953e-01,-2.617120e-01,-3.673154e-01
25%,-8.030752e-01,-3.112635e-01,-7.077987e-01,-8.317114e-01,-4.090806e-01,-2.959993e-01,-2.020215e-01,-1.479727e+00,-5.485287e-01,-3.272564e-01,...,-2.890930e-01,-1.463850e-01,-1.029597e-01,-1.463850e-01,-1.696378e-01,-2.062216e-01,-3.072259e-01,-2.324953e-01,-2.617120e-01,-3.673154e-01
50%,-2.143546e-01,-3.112635e-01,7.503166e-03,-1.341470e-01,-4.090806e-01,-2.959993e-01,-2.020215e-01,6.758005e-01,-4.790029e-01,-3.272564e-01,...,-2.890930e-01,-1.463850e-01,-1.029597e-01,-1.463850e-01,-1.696378e-01,-2.062216e-01,-3.072259e-01,-2.324953e-01,-2.617120e-01,-3.673154e-01
75%,6.098541e-01,2.970830e-01,3.651541e-01,5.634174e-01,-4.090806e-01,-2.959993e-01,-2.020215e-01,6.758005e-01,7.677196e-03,-3.272564e-01,...,-2.890930e-01,-1.463850e-01,-1.029597e-01,-1.463850e-01,-1.696378e-01,-2.062216e-01,-3.072259e-01,-2.324953e-01,-2.617120e-01,-3.673154e-01
max,6.732547e+00,1.550575e+01,5.372267e+00,6.143933e+00,2.444506e+00,8.821219e+00,1.654716e+01,6.758005e-01,7.794559e+00,3.055708e+00,...,9.632579e+00,6.831301e+00,9.712535e+00,6.831301e+00,5.894913e+00,4.849153e+00,3.254934e+00,4.301163e+00,3.820995e+00,2.722456e+00

In [101]:
# Save the new cleaned data
df.to_csv("cleaned_risk_factor_cervical_cancer.csv",index=False)