In [19]:
import pandas as pd

In [20]:
df = pd.read_csv("risk_factors_cervical_cancer.csv",na_values=['?',' ?','? '])

In [21]:
df.shape

(858, 36)

In [22]:
df.head()

,Age,Number of sexual partners,First sexual intercourse,Num of pregnancies,Smokes,Smokes (years),Smokes (packs/year),Hormonal Contraceptives,Hormonal Contraceptives (years),IUD,...,STDs: Time since first diagnosis,STDs: Time since last diagnosis,Dx:Cancer,Dx:CIN,Dx:HPV,Dx,Hinselmann,Schiller,Citology,Biopsy
0,18,4.0,15.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
1,15,1.0,14.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
2,34,1.0,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
3,52,5.0,16.0,4.0,1.0,37.0,37.0,1.0,3.0,0.0,...,NaN,NaN,1,0,1,0,0,0,0,0
4,46,3.0,21.0,4.0,0.0,0.0,0.0,1.0,15.0,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0

In [23]:
df.shape

(858, 36)

In [25]:
# Combine last four columns into one as a single target variable
x = (df['Hinselmann'] + df['Schiller'] + df['Citology'] + df['Biopsy'])
x.unique()

array([0, 3, 1, 2, 4], dtype=int64)

In [26]:
df['Cancer'] = (df['Hinselmann'] + df['Schiller'] + df['Citology'] + df['Biopsy'])

In [27]:
# Tune the decision variable for Binary classification 
df.loc[df['Cancer'] > 0, 'Cancer'] = 1

In [28]:
df['Cancer'].unique()

array([0, 1], dtype=int64)

In [29]:
df.head()

,Age,Number of sexual partners,First sexual intercourse,Num of pregnancies,Smokes,Smokes (years),Smokes (packs/year),Hormonal Contraceptives,Hormonal Contraceptives (years),IUD,...,STDs: Time since last diagnosis,Dx:Cancer,Dx:CIN,Dx:HPV,Dx,Hinselmann,Schiller,Citology,Biopsy,Cancer
0,18,4.0,15.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,0,0,0,0,0,0,0,0,0
1,15,1.0,14.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,0,0,0,0,0,0,0,0,0
2,34,1.0,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,0,0,0,0,0,0,0,0,0
3,52,5.0,16.0,4.0,1.0,37.0,37.0,1.0,3.0,0.0,...,NaN,1,0,1,0,0,0,0,0,0
4,46,3.0,21.0,4.0,0.0,0.0,0.0,1.0,15.0,0.0,...,NaN,0,0,0,0,0,0,0,0,0

In [30]:
df.dtypes

Age                                     int64
Number of sexual partners             float64
First sexual intercourse              float64
Num of pregnancies                    float64
Smokes                                float64
Smokes (years)                        float64
Smokes (packs/year)                   float64
Hormonal Contraceptives               float64
Hormonal Contraceptives (years)       float64
IUD                                   float64
IUD (years)                           float64
STDs                                  float64
STDs (number)                         float64
STDs:condylomatosis                   float64
STDs:cervical condylomatosis          float64
STDs:vaginal condylomatosis           float64
STDs:vulvo-perineal condylomatosis    float64
STDs:syphilis                         float64
STDs:pelvic inflammatory disease      float64
STDs:genital herpes                   float64
STDs:molluscum contagiosum            float64
STDs:AIDS                             float64
STDs:HIV                              float64
STDs:Hepatitis B                      float64
STDs:HPV                              float64
STDs: Number of diagnosis               int64
STDs: Time since first diagnosis      float64
STDs: Time since last diagnosis       float64
Dx:Cancer                               int64
Dx:CIN                                  int64
Dx:HPV                                  int64
Dx                                      int64
Hinselmann                              int64
Schiller                                int64
Citology                                int64
Biopsy                                  int64
Cancer                                  int64
dtype: object

In [36]:
df.isnull().all()

Age                                   False
Number of sexual partners             False
First sexual intercourse              False
Num of pregnancies                    False
Smokes                                False
Smokes (years)                        False
Smokes (packs/year)                   False
Hormonal Contraceptives               False
Hormonal Contraceptives (years)       False
IUD                                   False
IUD (years)                           False
STDs                                  False
STDs (number)                         False
STDs:condylomatosis                   False
STDs:cervical condylomatosis          False
STDs:vaginal condylomatosis           False
STDs:vulvo-perineal condylomatosis    False
STDs:syphilis                         False
STDs:pelvic inflammatory disease      False
STDs:genital herpes                   False
STDs:molluscum contagiosum            False
STDs:AIDS                             False
STDs:HIV                              False
STDs:Hepatitis B                      False
STDs:HPV                              False
STDs: Number of diagnosis             False
STDs: Time since first diagnosis      False
STDs: Time since last diagnosis       False
Dx:Cancer                             False
Dx:CIN                                False
Dx:HPV                                False
Dx                                    False
Hinselmann                            False
Schiller                              False
Citology                              False
Biopsy                                False
Cancer                                False
dtype: bool

In [31]:
# Drop columns which have all NaN values
l=df.columns[df.isnull().all()]
df.drop(l, inplace=True, axis=1)

In [38]:
df.shape

(858, 37)

In [39]:
df.isnull().sum()/df.shape[0] * 100

Age                                    0.000000
Number of sexual partners              3.030303
First sexual intercourse               0.815851
Num of pregnancies                     6.526807
Smokes                                 1.515152
Smokes (years)                         1.515152
Smokes (packs/year)                    1.515152
Hormonal Contraceptives               12.587413
Hormonal Contraceptives (years)       12.587413
IUD                                   13.636364
IUD (years)                           13.636364
STDs                                  12.237762
STDs (number)                         12.237762
STDs:condylomatosis                   12.237762
STDs:cervical condylomatosis          12.237762
STDs:vaginal condylomatosis           12.237762
STDs:vulvo-perineal condylomatosis    12.237762
STDs:syphilis                         12.237762
STDs:pelvic inflammatory disease      12.237762
STDs:genital herpes                   12.237762
STDs:molluscum contagiosum            12.237762
STDs:AIDS                             12.237762
STDs:HIV                              12.237762
STDs:Hepatitis B                      12.237762
STDs:HPV                              12.237762
STDs: Number of diagnosis              0.000000
STDs: Time since first diagnosis      91.724942
STDs: Time since last diagnosis       91.724942
Dx:Cancer                              0.000000
Dx:CIN                                 0.000000
Dx:HPV                                 0.000000
Dx                                     0.000000
Hinselmann                             0.000000
Schiller                               0.000000
Citology                               0.000000
Biopsy                                 0.000000
Cancer                                 0.000000
dtype: float64

In [32]:
# Drop columns which have NaN values greater than 90%
l=df.columns[(df.isnull().sum()/df.shape[0] * 100) > 90]
df.drop(l, inplace=True, axis=1)

In [33]:
df.shape

(858, 35)

In [42]:
# Find rows with missing values greater than 50%
df[    df.isnull().sum(axis=1)    >   (df.shape[1]/2)   ]
df = df[df.isnull().sum(axis=1) <=(df.shape[1]/2) ]

In [43]:
df.shape

(763, 35)

In [44]:
# Print colmuns that have minimum one NaN value
len(df.columns[df.isna().any()])

24

In [45]:
# Fill missing values with mode value for all columns which are float or int
for col in df.columns[df.isnull().any()]:
    df[col].fillna(df[col].mode()[0],inplace=True)
# Print remaining columns which still have NaN values
df.columns[df.isnull().any()]

Index([], dtype='object')

In [12]:
# Check those columns where all values are same
(df != df.iloc[0]).any()
# (df == df.iloc[0]).all()

Age                                   True
Number of sexual partners             True
First sexual intercourse              True
Num of pregnancies                    True
Smokes                                True
Smokes (years)                        True
Smokes (packs/year)                   True
Hormonal Contraceptives               True
Hormonal Contraceptives (years)       True
IUD                                   True
IUD (years)                           True
STDs                                  True
STDs (number)                         True
STDs:condylomatosis                   True
STDs:cervical condylomatosis          True
STDs:vaginal condylomatosis           True
STDs:vulvo-perineal condylomatosis    True
STDs:syphilis                         True
STDs:pelvic inflammatory disease      True
STDs:genital herpes                   True
STDs:molluscum contagiosum            True
STDs:AIDS                             True
STDs:HIV                              True
STDs:Hepatitis B                      True
STDs:HPV                              True
STDs: Number of diagnosis             True
STDs: Time since first diagnosis      True
STDs: Time since last diagnosis       True
Dx:Cancer                             True
Dx:CIN                                True
Dx:HPV                                True
Dx                                    True
Hinselmann                            True
Schiller                              True
Citology                              True
Biopsy                                True
Cancer                                True
dtype: bool

In [34]:
# Remove columns which have same value in all rows
df=df.loc[:, (df != df.iloc[0]).any()]
df.shape

(858, 35)

In [14]:
for col in df.columns:
    if len(df[col].unique()) == df.shape[0]:
        print(col)
#         df.drop(col,inplace=True,axis=1)

In [15]:
df.describe()

,Age,Number of sexual partners,First sexual intercourse,Num of pregnancies,Smokes,Smokes (years),Smokes (packs/year),Hormonal Contraceptives,Hormonal Contraceptives (years),IUD,...,STDs: Time since last diagnosis,Dx:Cancer,Dx:CIN,Dx:HPV,Dx,Hinselmann,Schiller,Citology,Biopsy,Cancer
count,858.000000,832.000000,851.000000,802.000000,845.000000,845.000000,845.000000,750.000000,750.000000,741.000000,...,71.000000,858.000000,858.000000,858.000000,858.000000,858.000000,858.000000,858.000000,858.000000,858.000000
mean,26.820513,2.527644,16.995300,2.275561,0.145562,1.219721,0.453144,0.641333,2.256419,0.112011,...,5.816901,0.020979,0.010490,0.020979,0.027972,0.040793,0.086247,0.051282,0.064103,0.118881
std,8.497948,1.667760,2.803355,1.447414,0.352876,4.089017,2.226610,0.479929,3.764254,0.315593,...,5.755271,0.143398,0.101939,0.143398,0.164989,0.197925,0.280892,0.220701,0.245078,0.323837
min,13.000000,1.000000,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,20.000000,2.000000,15.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,25.000000,2.000000,17.000000,2.000000,0.000000,0.000000,0.000000,1.000000,0.500000,0.000000,...,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,32.000000,3.000000,18.000000,3.000000,0.000000,0.000000,0.000000,1.000000,3.000000,0.000000,...,7.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,84.000000,28.000000,32.000000,11.000000,1.000000,37.000000,37.000000,1.000000,30.000000,1.000000,...,22.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [16]:
# Normalize the data
from sklearn import preprocessing

x = df.values #returns a numpy array
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
df = pd.DataFrame(x_scaled,columns=df.columns)

In [55]:
df.describe()

,Age,Number of sexual partners,First sexual intercourse,Num of pregnancies,Smokes,Smokes (years),Smokes (packs/year),Hormonal Contraceptives,Hormonal Contraceptives (years),IUD,...,STDs: Number of diagnosis,Dx:Cancer,Dx:CIN,Dx:HPV,Dx,Hinselmann,Schiller,Citology,Biopsy,Cancer
count,763.000000,763.000000,763.000000,763.000000,763.000000,763.000000,763.000000,763.000000,763.000000,763.000000,...,763.000000,763.000000,763.000000,763.000000,763.000000,763.000000,763.000000,763.000000,763.000000,763.000000
mean,0.200026,0.056065,0.321339,0.202907,0.141547,0.032973,0.012489,0.647444,0.073932,0.108781,...,0.032765,0.023591,0.010485,0.023591,0.030144,0.045872,0.096986,0.055046,0.072084,0.131062
std,0.121949,0.061582,0.128663,0.132386,0.348813,0.111909,0.061812,0.478079,0.124781,0.311569,...,0.106392,0.151871,0.101925,0.151871,0.171096,0.209344,0.296132,0.228219,0.258796,0.337689
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.112676,0.037037,0.227273,0.090909,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.183099,0.037037,0.318182,0.181818,0.000000,0.000000,0.000000,1.000000,0.014000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.281690,0.074074,0.363636,0.272727,0.000000,0.000000,0.000000,1.000000,0.100000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [52]:
from sklearn import preprocessing
x = df.values #returns a numpy array
min_max_scaler = preprocessing.StandardScaler()
x_scaled_std = min_max_scaler.fit_transform(x)
df = pd.DataFrame(x_scaled_std,columns=df.columns)

In [53]:
df.describe()

,Age,Number of sexual partners,First sexual intercourse,Num of pregnancies,Smokes,Smokes (years),Smokes (packs/year),Hormonal Contraceptives,Hormonal Contraceptives (years),IUD,...,STDs: Number of diagnosis,Dx:Cancer,Dx:CIN,Dx:HPV,Dx,Hinselmann,Schiller,Citology,Biopsy,Cancer
count,7.630000e+02,7.630000e+02,7.630000e+02,7.630000e+02,7.630000e+02,7.630000e+02,7.630000e+02,7.630000e+02,7.630000e+02,7.630000e+02,...,7.630000e+02,7.630000e+02,7.630000e+02,7.630000e+02,7.630000e+02,7.630000e+02,7.630000e+02,7.630000e+02,7.630000e+02,7.630000e+02
mean,-4.613319e-16,-1.716990e-17,1.260096e-16,3.403423e-16,-4.467083e-17,-1.382322e-17,-4.840310e-16,-3.361226e-16,6.904336e-17,-1.369227e-16,...,-2.764644e-16,-3.284107e-16,-2.284833e-16,-2.865045e-16,1.161878e-16,1.001820e-16,-1.223719e-16,-2.302658e-16,1.328484e-16,-1.261551e-16
std,1.000656e+00,1.000656e+00,1.000656e+00,1.000656e+00,1.000656e+00,1.000656e+00,1.000656e+00,1.000656e+00,1.000656e+00,1.000656e+00,...,1.000656e+00,1.000656e+00,1.000656e+00,1.000656e+00,1.000656e+00,1.000656e+00,1.000656e+00,1.000656e+00,1.000656e+00,1.000656e+00
min,-1.641323e+00,-9.110204e-01,-2.499163e+00,-1.533698e+00,-4.060610e-01,-2.948353e-01,-2.021813e-01,-1.355150e+00,-5.928870e-01,-3.493692e-01,...,-3.081700e-01,-1.554383e-01,-1.029370e-01,-1.554383e-01,-1.762983e-01,-2.192645e-01,-3.277225e-01,-2.413554e-01,-2.787178e-01,-3.883678e-01
25%,-7.167533e-01,-3.091948e-01,-7.315865e-01,-8.465508e-01,-4.060610e-01,-2.948353e-01,-2.021813e-01,-1.355150e+00,-5.928870e-01,-3.493692e-01,...,-3.081700e-01,-1.554383e-01,-1.029370e-01,-1.554383e-01,-1.762983e-01,-2.192645e-01,-3.277225e-01,-2.413554e-01,-2.787178e-01,-3.883678e-01
50%,-1.388975e-01,-3.091948e-01,-2.455610e-02,-1.594037e-01,-4.060610e-01,-2.948353e-01,-2.021813e-01,7.379258e-01,-4.806167e-01,-3.493692e-01,...,-3.081700e-01,-1.554383e-01,-1.029370e-01,-1.554383e-01,-1.762983e-01,-2.192645e-01,-3.277225e-01,-2.413554e-01,-2.787178e-01,-3.883678e-01
75%,6.701007e-01,2.926308e-01,3.289591e-01,5.277434e-01,-4.060610e-01,-2.948353e-01,-2.021813e-01,7.379258e-01,2.090434e-01,-3.493692e-01,...,-3.081700e-01,-1.554383e-01,-1.029370e-01,-1.554383e-01,-1.762983e-01,-2.192645e-01,-3.277225e-01,-2.413554e-01,-2.787178e-01,-3.883678e-01
max,6.564230e+00,1.533827e+01,5.278172e+00,6.024920e+00,2.462684e+00,8.646854e+00,1.598640e+01,7.379258e-01,7.426416e+00,2.862302e+00,...,9.097179e+00,6.433420e+00,9.714680e+00,6.433420e+00,5.672205e+00,4.560702e+00,3.051362e+00,4.143268e+00,3.587858e+00,2.574879e+00

In [56]:
df.to_csv("clean_CC.csv")